language: c

sudo: false

before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/lathoub/Arduino-AppleMidi-Library/master/install.sh)

script:
  - build_platform mega
  - build_platform esp8266

notifications:
  email:
    on_success: change
    on_failure: change
