INC=-I..
OBJ=../ReadFingeringTree.cpp
#  -target x86_64-apple-darwin16.7.0-macho
# OPT=-ffast-math -msoft-float -mno-implicit-float
# OPT=-target arm-none-eabi -mcpu=cortex-m4
# OPT=-ffast-math
all:
	clang -g -I.. $(OPT) finger.cpp $(OBJ)